### PR TITLE
Changed method to transformRingToRightHandedCSKeepAllCoords in validSurfaceOrientation test.

### LINKED ISSUE #26: Test method validSurfaceOrientation: Ring has fewer than 3 points
With reference to the' _Fix #20: Reduce tolerance for detecting consecutive duplicate positions_' , I am retesting - using release 1.25 - some of the files which failed with previous releases due to both ‘_Exterior boundary is not simple_’ and ‘_Ring has fewer than 3 points_’ errors. While the ‘_exterior boundary_’ issue is no more there, the ‘_Ring has fewer than 3 points_’ error is still reported. Of course no geometry in the file has only two points, so the error should depend, also in this case, on tolerance for detecting consecutive duplicate positions. The error message does not report the identifier of the failing polygon (and this issue should be solved as well), but there is only one 'small polygon' in the file, the same for which previously the "boundary is not simple" error was reported. 
Could you help ?
Thank you
Stefania
[example.3points.zip](https://github.com/opengeospatial/ets-gml32/files/881954/example.3points.zip)

### PR DESCRIPTION
**Pull request by keshav-nangare**
Fixed #26.

Before merging this PR, the following changes should be done:
  1. Release of the geomatic-geotk project as the new method added in GeodesyUtils class.
  2. The release version of the geomatic-geotk should be updated in current PR.

This PR is dependent on https://github.com/opengeospatial/geomatics-geotk/pull/2.

### CODE REVIEW

**Review by dstenger — CHANGES_REQUESTED** [review]
When I am testing this fix with the reference implementation [1], I am getting following new test failures:

- declares GML Objects | No GML object or property definitions were found in the schema.
- import Full GML Schema | java.lang.AssertionError: Unexpected number of  imported GML element declarations. The full GML schema (gml.xsd) must be  imported.                      expected <br>[474] but found <br>[0]
- substitutes For Abstract Feature | java.lang.NullPointerException

@keshav-nangare Can you please check why those new failures occur?

[1] http://cite.deegree.org/deegree-webservices-3.4.12/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos

**Comment by keshav-nangare** [comment]
@dstenger 

I am able to reproduce the reported behavior and found the issue in the `targetNamespace` of the following code snippet: https://github.com/opengeospatial/ets-gml32/blob/5075bb4d9dac52033375e96c34b63171d689d1c8/src/main/java/org/opengis/cite/iso19136/general/GeneralSchemaTests.java#L199-L205
We had issue #46 regarding `targetNamespace` which was fixed using the #53. These changes are currently available in `master` but not in `issue#26` branch. 

I am able to execute the test suite successfully by merging `master` into `issue#26` branch on the local machine. 
Can you give one try by merging `master` into `issue#26` and let me know if you still get these errors?

**Review by dstenger — APPROVED** [review]
Functional test was successful.

**Comment by dstenger** [comment]
Merge is currently blocked as geomatic-geotk has to be released first (see first comment of PR).

**Comment by dstenger** [comment]
geomatics-geotk dependency was updated: https://github.com/opengeospatial/ets-gml32/issues/56

**Pull request merged**
